site_name: guizero
pages:
  - About: about.md
  - Installation: index.md
  - Using guizero:
      - Getting Started: start.md
      - Layouts: layout.md
      - Sizes: size.md
      - Colors: colors.md
      - Images: images.md
      - Alerts: alerts.md
      - Using tkinter methods: usingtk.md
      - Loops and sleeping: blocking.md
      - Examples and resources: resources.md
  - Widgets:
      - App: app.md
      - Box: box.md
      - ButtonGroup: buttongroup.md
      - CheckBox: checkbox.md
      - Combo: combo.md
      - MenuBar: menubar.md
      - Picture: picture.md
      - PushButton: pushbutton.md
      - Slider: slider.md
      - Text: text.md
      - TextBox: textbox.md
      - Waffle: waffle.md
  - Contributing: 
      - Notes: contributing.md
      - Developing: development.md
      - Deploying: deployment.md
  - Change log: changelog.md
theme: readthedocs
